# GNU coreutils #https://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities
brew "coreutils"
brew "findutils"
brew "gnu-indent"
brew "gnu-getopt"
brew "gnu-sed"
brew "gnutls"
brew "grep"
brew "ripgrep"
brew "gnu-tar"
brew "gawk"
brew "watchman"

# Binaries
brew "bat"
brew "diff-so-fancy"
# brew "exa" # deprecated as of 2024 use lsd instead
brew "lsd"
brew "rsync"
brew "fd"
brew "fzf"
brew "gh"
brew "htop"
brew "imagemagick"
brew "git"
brew "git-lfs"
brew "grex" # grep regex
brew "mas"
brew "m-cli"
brew "ripgrep"
brew "tig"
brew "thefuck"
brew "tmux"
brew "tldr"
brew "zsh"
brew "zoxide"
brew "zplug"
brew "tpm"

# for hackathons and experiments
brew "http-server"
cask "ngrok"

tap "homebrew/services" # https://thoughtbot.com/blog/starting-and-stopping-background-services-with-homebrew
# development
brew "yarn"
brew "postgresql"
brew "redis"

# tap 'homebrew/cask-fonts' # deprecated

# JS development
# brew "nvm" # installed by zsh plugin
brew "yarn"

# Fonts
# https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-dejavusansmono-nerd-font.rb
cask "font-dejavu-sans-mono" # for editor i.e. vscode, cursor, windsurf etc.
cask "font-dejavu-sans-mono-nerd-font" # for iterm lsd

# Apps
# cask "bartender"
cask "charles"
cask "docker"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "imageoptim"
cask "insomnia"
cask "iterm2"
cask "postman"
cask "slack"
cask "spectacle"
cask "spotify"
cask "sublime-text"
cask "the-unarchiver"
cask "visual-studio-code"
cask "cursor"
cask "vlc"
cask "tableplus"
cask "raycast"
# cask "sketch"
# TODO: check mackup https://github.com/lra/mackup

# AppStore Apps
# mas "1Password 7", id: 1333542190
# mas "Slack", id: 803453959 # prefer brew cask formula since it doesn't require appstore login
# mas "Spark", id: 1176895641
# mas "Todoist", id: 585829637
# mas "ToothFairy", id: 1191449274
# mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
