#!/usr/bin/env bash
# Requires: brew install dotbot (included in Brewfile)

set -e

CONFIG="install.conf.yaml"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
dotbot -d "${BASEDIR}" -c "${CONFIG}" "${@}"
