" Sensible defaults inspired from here: https://gist.github.com/simonista/8703722

" TODO: Load plugins here

" Turn on syntax highlighting
syntax on


" TODO: Pick a leader key
" let mapleader = ","

" Show line numbers
set number

" Encoding
set encoding=utf-8

" Whitespace
set wrap
set textwidth=79
set formatoptions=tcqrn1
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noshiftround

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
