" Sensible defaults for casual vim use
" Inspired by: https://gist.github.com/simonista/8703722

syntax on
set number
set encoding=utf-8
set mouse=a                      " enable mouse
set clipboard=unnamed            " use system clipboard
set backspace=indent,eol,start   " backspace works normally

" Whitespace
set wrap
set textwidth=79
set formatoptions=tcqrn
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noshiftround

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch

let $LOCALFILE=expand("~/.vimrc_local")
if filereadable($LOCALFILE)
    source $LOCALFILE
endif
